apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-rate-app
  labels:
    app: exchange-rate-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exchange-rate-app
  template:
    metadata:
      labels:
        app: exchange-rate-app
    spec:
      containers:
      - name: exchange-rate-app
        image: johntoby/exchange-rate-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5