apiVersion: v1
kind: Service
metadata:
  name: exchange-rate-service
  labels:
    app: exchange-rate-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: exchange-rate-app